name: Midway-GraphQL-Starter

on:
  push:
    branches: [master, main]
  # pull_request:
  #   branches: [master, main]

jobs:
  build:
    name: Build

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          yarn

      - name: Build
        run: |
          yarn prisma
          yarn build

  test-check:
    name: Unit Test & CodeCov Report

    strategy:
      matrix:
        node-version: [14.x]
        os: [macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          yarn

      - name: Unit Test & Codecov Report
        if: runner.os != 'Windows'
        run: |
          yarn test
          # bash <(curl -s https://codecov.io/bash)
